services:
  web:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STAARK_DATA_SOURCE: postgres
      STAARK_DATA_FALLBACK: none
      STAARK_TRUST_PROXY: "1"
      STAARK_TENANT_SITE_KEY_FALLBACK: "0"
      STAARK_SITE_KEY: ""
    ports: !override []
    networks:
      - staark-network

networks:
  staark-network:
    external: true