import {
  defineBlock,
  type BlockDefinition,
  type BlockField,
} from "@staark/theme-kit/block";

const EYEBROW: BlockField = {
  name: "eyebrow",
  label: "Eyebrow",
  type: "text",
  help: "Small label above the heading.",
};

export const elBlockDefinitions = [
  defineBlock({
    type: "emergencyBanner",
    label: "Jour banner",
    description: "Jour strip under the header plus a sticky call/quote bar on phones.",
    icon: "phone",
    category: "contact",
    version: 2,
    fields: [
      { name: "text", label: "Text", type: "text", placeholder: "Jour dygnet runt vid strömavbrott" },
      { name: "phone", label: "Phone", type: "text", help: "Leave empty to use the site phone number." },
      { name: "note", label: "Note", type: "text", help: "Short extra line, e.g. F-skatt · Org.nr. Hidden on phones." },
      {
        name: "mobileBar",
        label: "Mobile call/quote bar",
        type: "object",
        fields: [
          { name: "enabled", label: "Show on phones", type: "boolean" },
          { name: "callLabel", label: "Call label", type: "text", placeholder: "Ring" },
          { name: "quoteLabel", label: "Quote label", type: "text", placeholder: "Begär offert" },
          { name: "quoteHref", label: "Quote link", type: "text", placeholder: "#offert" },
        ],
      },
    ],
    required: [],
    defaults: {
      text: "Jour dygnet runt vid strömavbrott",
      mobileBar: { enabled: true, quoteHref: "#offert" },
    },
  }),
  defineBlock({
    type: "credentials",
    label: "Credentials",
    description: "Authorization, insurance and a link to the public register.",
    icon: "shield",
    category: "trust",
    version: 2,
    fields: [
      {
        name: "items",
        label: "Credentials",
        type: "array",
        itemLabel: "{title}",
        fields: [
          { name: "title", label: "Title", type: "text" },
          { name: "text", label: "Text", type: "text" },
        ],
      },
      { name: "registration", label: "Registration line", type: "text", placeholder: "Registrerat elinstallationsföretag · Org.nr …" },
      { name: "verify", label: "Verify link", type: "link", help: "Link to the public register so customers can check you." },
    ],
    required: [],
    defaults: {
      items: [
        { title: "Auktoriserad elinstallatör", text: "Behörighet enligt Elsäkerhetsverket" },
        { title: "Ansvarsförsäkring", text: "För allt arbete vi utför" },
        { title: "Garanti", text: "På arbete och material" },
      ],
      verify: { label: "Kontrollera oss hos Elsäkerhetsverket", href: "https://www.elsakerhetsverket.se/" },
    },
  }),
  defineBlock({
    type: "deductionCalculator",
    label: "ROT & grön teknik",
    description: "Price after ROT or grön teknik deduction, with editable rates.",
    icon: "calculator",
    category: "tools",
    version: 2,
    fields: [
      EYEBROW,
      { name: "heading", label: "Heading", type: "text" },
      { name: "intro", label: "Intro", type: "textarea" },
      { name: "points", label: "Bullet points", type: "array", itemLabel: "{value}", fields: [{ name: "value", label: "Point", type: "text" }] },
      {
        name: "options",
        label: "Job types",
        type: "array",
        itemLabel: "{label}",
        help: "2026: laddbox 50 %, batterilager 50 %, solceller 15 % (grön teknik); ROT 30 %.",
        fields: [
          { name: "label", label: "Label", type: "text" },
          { name: "kind", label: "Deduction", type: "select", options: [{ label: "Grön teknik (arbete + material)", value: "green" }, { label: "ROT (arbete)", value: "rot" }] },
          { name: "rate", label: "Rate (%)", type: "number", min: 0, max: 100 },
          { name: "defaultLabor", label: "Default labour (kr)", type: "number", min: 0 },
          { name: "defaultMaterial", label: "Default material (kr)", type: "number", min: 0 },
        ],
      },
      { name: "capPerPerson", label: "Max per person and year (kr)", type: "number", min: 0 },
      { name: "maxAmount", label: "Slider max (kr)", type: "number", min: 10000 },
      { name: "note", label: "Fine print", type: "text" },
    ],
    required: ["heading"],
    defaults: {
      eyebrow: "Avdrag",
      heading: "Vad kostar det efter avdrag?",
      capPerPerson: 50000,
    },
  }),
  defineBlock({
    type: "faq",
    label: "FAQ",
    description: "Questions and answers with FAQ structured data.",
    icon: "message-circle",
    category: "content",
    version: 2,
    fields: [
      EYEBROW,
      { name: "heading", label: "Heading", type: "text" },
      { name: "intro", label: "Intro", type: "textarea" },
      {
        name: "items",
        label: "Questions",
        type: "array",
        itemLabel: "{question}",
        fields: [
          { name: "question", label: "Question", type: "text" },
          { name: "answer", label: "Answer", type: "textarea" },
        ],
      },
      { name: "structuredData", label: "Add FAQ structured data (SEO)", type: "boolean" },
    ],
    required: ["heading"],
    defaults: {
      eyebrow: "Frågor",
      heading: "Vanliga frågor",
      items: [{ question: "Får jag byta ett vägguttag själv?", answer: "Svar…" }],
    },
  }),
  defineBlock({
    type: "quoteRequest",
    label: "Quote request",
    description: "Three-step quote form (job, details, contact) that lands in S-Hub Inbox.",
    icon: "clipboard",
    category: "forms",
    version: 2,
    fields: [
      EYEBROW,
      { name: "heading", label: "Heading", type: "text" },
      { name: "intro", label: "Intro", type: "textarea" },
      { name: "formId", label: "Form ID", type: "text", help: "Identifies the form in the Inbox." },
      { name: "areasLabel", label: "Areas label", type: "text", placeholder: "Vi arbetar i" },
      { name: "areas", label: "Service areas", type: "array", itemLabel: "{value}", fields: [{ name: "value", label: "Area", type: "text" }] },
      { name: "jobTypes", label: "Job types", type: "array", itemLabel: "{value}", fields: [{ name: "value", label: "Job type", type: "text" }] },
      { name: "timings", label: "Start options", type: "array", itemLabel: "{value}", fields: [{ name: "value", label: "Option", type: "text" }] },
      { name: "submitLabel", label: "Submit label", type: "text" },
      { name: "successMessage", label: "Success message", type: "text" },
      { name: "consent", label: "Consent / privacy text", type: "textarea" },
    ],
    required: ["heading", "formId"],
    defaults: {
      eyebrow: "Offert",
      heading: "Berätta vad du behöver",
      formId: "el-offert",
      areas: [],
    },
  }),
] satisfies readonly BlockDefinition[];
